name: Debug Build and Test

on:
  push:
    tags:
      - '*'

jobs:
  build-release:
    runs-on: windows-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

    steps:
      - name: Checkout and initialise
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Extract Dalamud version
        id: dalamud-version
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: "./XIVAuras/XIVAuras.csproj"
          xpath: "//DalamudVersion"

      - name: CSProj Cache
        id: cache-csproj
        uses: actions/cache@v2
        with:
          path: |
            ./dalamud
            ~/.nuget/packages
          key: ${{ runner.os }}-csproj-v3-${{ hashFiles('**/*.csproj') }}

      - name: Setup Dalamud
        if: |
          steps.cache-csproj.outputs.cache-hit != 'true' &&
          steps.dalamud-version.outputs.info != 'dev'
        shell: pwsh
        run: |
          mkdir ./dalamud
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile ./dalamud/latest.zip
          Expand-Archive -Path ./dalamud/latest.zip ./dalamud

      - name: Setup dev Dalamud
        if: |
          steps.cache-csproj.outputs.cache-hit != 'true' &&
          steps.dalamud-version.outputs.info == 'dev'
        shell: pwsh
        run: |
          mkdir ./dalamud
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile ./dalamud/latest.zip
          Expand-Archive -Path ./dalamud/latest.zip ./dalamud

      - name: Restore project dependencies
        run: dotnet restore --verbosity normal

      - name: Build Release
        run: dotnet build --no-restore --verbosity normal --configuration Release

      - name: Test Release
        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: XIVAuras-debug-${{ github.sha }}
          path: |
            XIVAuras/bin/x64/Release
            !XIVAuras/bin/x64/Release/XIVAuras
